### ISSUE TITLE
AttentionUNet, missing one UpSample?

### ISSUE THREAD

**Issue by brechmos** [bo-10000/VoxResNet#1]
Thank you for coding this, but when I tried it my output of the model was decimated by a factor of 2 compared to the input.  Is there a missing UpSample at the end?

My input data is, for example, [128, 128, 128] and the segmentation is [64, 64, 64].

**Comment by bo-10000** [comment]
you are right. There was one more max pooling in the encoder part and I updated the code. Thank you for reporting issue!
